install.packages("ggthemes")
install.packages("ggrepel")
install.packages("gridExtra")
install.packages("ggridges")

library(dslabs)
library(tidyverse)
library(dplyr)
library(ggthemes)
library(ggrepel)
library(gridExtra)
library(ggridges)
library(ggplot2)
data(murders)
data(heights)
data(gapminder)